USE `rent-a-car`;

INSERT INTO `rent-a-car`.`users` (`id`, `first_name`, `last_name`, `email`, `phone_number`, `username`, `password`, `repeat_password`, `role`) VALUES ('1', 'Silviya', 'Yankova', 'silviya@rentacar.com', '0898405658', 'silviya', '8101308797Ja*', '8101308797Ja*', 'ADMINISTRATOR');
INSERT INTO `rent-a-car`.`users` (`id`, `first_name`, `last_name`, `email`, `phone_number`, `username`, `password`, `repeat_password`, `role`) VALUES ('2', 'Kalina', 'Dimitrova', 'kalina@rentacar.com', '0898405658', 'kalina', '8101308797Ja*', '8101308797Ja*', 'SELLER');
INSERT INTO `rent-a-car`.`users` (`id`, `first_name`, `last_name`, `email`, `phone_number`, `username`, `password`, `repeat_password`, `role`) VALUES ('3', 'Stefan', 'Hristov', 'stefan@rentacar.com', '0898405658', 'stefan', '8101308797Ja*', '8101308797Ja*', 'SITE_MANAGER');
INSERT INTO `rent-a-car`.`users` (`id`, `first_name`, `last_name`, `email`, `phone_number`, `username`, `password`, `repeat_password`, `role`) VALUES ('4', 'Kristina', 'Dimitrova', 'kristina@rentacar.com', '0898405658', 'kristina', '8101308797Ja*', '8101308797Ja*', 'DRIVER');
INSERT INTO `rent-a-car`.`users` (`id`, `first_name`, `last_name`, `email`, `phone_number`, `username`, `password`, `repeat_password`, `role`) VALUES ('5', 'Petar', 'Arsov', 'petar@rentacar.com', '0898405658', 'petar', '8101308797Ja*', '8101308797Ja*', 'DRIVER');
INSERT INTO `rent-a-car`.`users` (`id`, `first_name`, `last_name`, `email`, `phone_number`, `username`, `password`, `repeat_password`, `role`) VALUES ('6', 'Martin', 'Yankov', 'martin@user.com', '0898405658', 'martin', '8101308797Ja*', '8101308797Ja*', 'USER');
INSERT INTO `rent-a-car`.`users` (`id`, `first_name`, `last_name`, `email`, `phone_number`, `username`, `password`, `repeat_password`, `role`) VALUES ('7', 'Daniel', 'Petkov', 'daniel@user.com', '0898405658', 'daniel', '8101308797Ja*', '8101308797Ja*', 'USER');


INSERT INTO `rent-a-car`.`workers` (`id`, `first_name`, `last_name`, `code`, `worker_status`) VALUES ('1', 'Stanimir', 'Petrov', 'C1', 'AVAILABLE');
INSERT INTO `rent-a-car`.`workers` (`id`, `first_name`, `last_name`, `code`, `worker_status`) VALUES ('2', 'Dimitar', 'Ivanov', 'C2', 'AVAILABLE');
INSERT INTO `rent-a-car`.`workers` (`id`, `first_name`, `last_name`, `code`, `worker_status`) VALUES ('3', 'Petq', 'Ivanova', 'C3', 'AVAILABLE');
INSERT INTO `rent-a-car`.`workers` (`id`, `first_name`, `last_name`, `code`, `worker_status`) VALUES ('4', 'Diana', 'Mihova', 'C4', 'AVAILABLE');

INSERT INTO `rent-a-car`.`cars` (`id`, `brand`, `model`, `year`, `picture_url`, `color`, `car_type`, `doors`, `seats`, `conveniences`, `entertainments`, `drivetrain`, `transmission`, `horse_powers`, `fuel_type`, `tank_volume`, `fuel_consumption`, `deposit`, `price_per_day`, `car_status`) VALUES ('1', 'BMW', '330 i', '2021', 'https://cdn.bmwblog.com/wp-content/uploads/2021/02/The-New-BMW-330i-Iconic-Edition-in-Mineral-White-metallic-1.jpg', 'Mineral White Metallic', 'HATCHBACK', '4', '4', 'Heated Seats, Keyless Start, Navigation System', 'Bluetooth, HomeLink', 'REAR_WHEEL_DRIVE', 'AUTOMATIC', '255', 'GASOLINE', '58', '7.9', '150', '28.22', 'AVAILABLE');
INSERT INTO `rent-a-car`.`cars` (`id`, `brand`, `model`, `year`, `picture_url`, `color`, `car_type`, `doors`, `seats`, `conveniences`, `entertainments`, `drivetrain`, `transmission`, `horse_powers`, `fuel_type`, `tank_volume`, `fuel_consumption`, `deposit`, `price_per_day`, `car_status`) VALUES ('2', 'Citroen', 'C3', '2020', 'https://www.netcarshow.com/Citroen-C3-2020-1024-01.jpg', 'Red', 'SEDAN', '5', '5', 'Heated Seats, Keyless Start, Navigation System', 'Bluetooth, HomeLink', 'FRONT_WHEEL_DRIVE', 'MANUAL', '83', 'GASOLINE', '45', '4.2', '100', '20', 'AVAILABLE');
INSERT INTO `rent-a-car`.`cars` (`id`, `brand`, `model`, `year`, `picture_url`, `color`, `car_type`, `doors`, `seats`, `conveniences`, `entertainments`, `drivetrain`, `transmission`, `horse_powers`, `fuel_type`, `tank_volume`, `fuel_consumption`, `deposit`, `price_per_day`, `car_status`) VALUES ('3', 'Peugeot', '308', '2019', 'https://www.auto-data.net/images/f99/Peugeot-3008-II-facelift-2020_3.jpg', 'Blue', 'SEDAN', '5', '5', 'Heated Seats, Keyless Start, Navigation System', 'Bluetooth, HomeLink', 'FRONT_WHEEL_DRIVE', 'MANUAL', '90', 'GASOLINE', '45', '5', '100', '20', 'AVAILABLE');
INSERT INTO `rent-a-car`.`cars` (`id`, `brand`, `model`, `year`, `picture_url`, `color`, `car_type`, `doors`, `seats`, `conveniences`, `entertainments`, `drivetrain`, `transmission`, `horse_powers`, `fuel_type`, `tank_volume`, `fuel_consumption`, `deposit`, `price_per_day`, `car_status`) VALUES ('4', 'Dodge ', 'Durango SXT', '2020', 'https://pictures.dealer.com/h/hughwhitecdjampcllc/0133/33fd4cd4038c9b5ee446d3741806dfc0x.jpg?impolicy=downsize&w=568', 'Octane Red Pearlcoat', 'SUV', '4', '5', 'Heated Seats, Keyless Start, Navigation System', 'Bluetooth, HomeLink', 'ALL_WHEEL_DRIVE', 'AUTOMATIC', '293', 'GASOLINE', '93', '18', '200', '35', 'AVAILABLE');
INSERT INTO `rent-a-car`.`cars` (`id`, `brand`, `model`, `year`, `picture_url`, `color`, `car_type`, `doors`, `seats`, `conveniences`, `entertainments`, `drivetrain`, `transmission`, `horse_powers`, `fuel_type`, `tank_volume`, `fuel_consumption`, `deposit`, `price_per_day`, `car_status`) VALUES ('5', 'Chevrolet ', 'Spark LS', '2022', 'https://www.ccarprice.com/products/Chevrolet_Spark_LS_2022_1.jpg', ' Caribben Blue', 'HATCHBACK', '4', '4', 'Heated Seats, Keyless Start, Navigation System', 'Bluetooth, HomeLink', 'FRONT_WHEEL_DRIVE', 'MANUAL', '98', 'DIESEL', '34', '7.6', '160', '30', 'AVAILABLE');
